CREATE TABLE IF NOT EXISTS profile(user VARCHAR NOT NULL, num INTEGER NOT NULL, state VARCHAR NOT NULL, lang VARCHAR NOT NULL, pass TEXT NOT NULL);
SELECT * FROM profile;
CREATE TABLE IF NOT EXISTS login(user varchar NOT NULL,pass TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS predicted_price(state VARCHAR NOT NULL,price INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS crop(user VARCHAR NOT NULL,crop VARCHAR NOT NULL);


